### ISSUE TITLE
error on line 45

### ISSUE THREAD

**Issue by KhanalSisam** [Prabesh-Shrestha/Pycoder#1]
Traceback (most recent call last):
  File "<stdin>", line 45, in <module>
NameError: "editor" object is not defined or is out of scope
Reference:  look [http://bitly.com/98K8eH](http://bitly.com/98K8eH)

ke ho bhanera try garna khojeko, code nai kam garena.
very disappointed in you

**Comment by Prabesh-Shrestha** [comment]
lol 
nice 
social credits > 9000
https://www.youtube.com/watch?v=46pra8NwhzU
